### ISSUE TITLE
error on running $ node app

### ISSUE THREAD

**Issue by opnsrcntrbtr** [Learn2Crack/android-gcm-server-node#1]
$ node app
module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ianpinto/Documents/node/android-gcm-server-node/functions/register.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ianpinto/Documents/node/android-gcm-server-node/routes/routes.js:2:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
Ians-MacBook-Pro:android-gcm-server-node ianpinto$

**Comment by rajamalw** [comment]
Have you used `npm install` before running the command ?

**Comment by breogangf** [comment]
You should close this issue.
